name: 'Docker Image build and push to GitHub Container Registry'
description: 'Builds and pushes Docker image to GitHub Container Registry'
author: nuno marcelino

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  registry:
    description: 'Where to push image'
    default: ghcr.io
    required: false
  username:
    description: 'Username to login to registry'
  password:
    description: 'Token to login'

runs:
  using: "composite"
  steps:
  - name: Login to registry
    run: |
      docker login ${{ inputs.registry }} -u ${{ inputs.username }} -p ${{ inputs.password }}
    shell: bash

  - name: Test just output the message
    uses: profy12/lowercase-action@0.6
    id: lowered
    with:
      text: ${{ github.repository }}

  - name: Set up buildx
    run: |
      docker run --privileged --rm tonistiigi/binfmt --install all
      docker buildx create --use
    shell: bash

  - name: Build image (multi-architecture)
    run: |
      docker buildx build --platform linux/amd64,linux/arm64 -t ${{ inputs.registry }}/${{ steps.lowered.outputs.text }}/${{ inputs.image-name }} . --push
    shell: bash

  - name: Push image
    run: |
      docker push ${{ inputs.registry }}/${{ steps.lowered.outputs.text }}/${{ inputs.image-name }}
    shell: bash
