name: 'Docker Image build and push to GitHub Container Registry'
description: 'Builds and pushes Docker image to GitHub Container Registry'

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  image:
    description: 'Nom de l’image Docker'
    required: true
  tag:
    description: 'Numéro de tag (par défaut nom de la branche)'
  context:
    description: 'Contexte de construction (par défaut .)'
    default: '.'
  github-token:
    description: 'Token GitHub'
    required: true
runs:
  using: 'composite'
  steps:
  - shell: /bin/bash
    run: echo "image=${{ inputs.image }}" >> $GITHUB_ENV
  - shell: /bin/bash
    run: echo "tag=${{ inputs.tag }}" >> $GITHUB_ENV
  - shell: /bin/bash
    run: echo "context=${{ inputs.context }}" >> $GITHUB_ENV
  - shell: /bin/bash
    run: echo "github-token=${{ inputs.github-token }}" >> $GITHUB_ENV
  - shell: /bin/bash
    run: echo "::set-output name=imageTag::branch-\${{ github.ref_slug }}"
  - shell: /bin/bash
    run: docker build -t ${{ inputs.image }}:${{ env.imageTag }} -f ${{ inputs.context }}/Dockerfile ${{ inputs.context }}
  - shell: /bin/bash
    run: docker login ghcr.io -u ${{ github.actor }} -p ${{ inputs.github-token }}
  - name: user-to-lowercase
    uses: profy12/lowercase-action@0.5
    with:
      text: ${{ github.repository_owner }}
    id: user-to-lowercase
  - name: repo-to-lowercase
    uses: profy12/lowercase-action@0.5
    with:
      text: ${{ github.repository_name }}
    id: repo-to-lowercase
  - shell: /bin/bash
    run: docker push ghcr.io/${{ steps.user-to-lowercase.outputs.text }}/${{ steps.repo-to-lowercase.outputs.text }}:${{ env.imageTag }}
