name: 'Docker Image build and push to GitHub Container Registry'
description: 'Builds and pushes Docker image to GitHub Container Registry'
author: nuno marcelino

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  file:
    description: 'Nom du fichier Dockerfile'
    required: true
  image:
    description: 'Nom de l’image Docker'
    required: true
  tag:
    description: 'Numéro de tag (par défaut nom de la branche)'
  context:
    description: 'Contexte de construction (par défaut .)'
    default: '.'
  github-token:
    description: 'Token GitHub'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Build Docker Image
    run: |
      docker build -t ${{ inputs.image }} -f ${{ inputs.file }} ${{ inputs.context }}
    shell: bash

  - name: Docker Login
    run: |
      docker login ghcr.io -u ${{ github.actor }} -p ${{ inputs.github-token }}
    shell: bash

  - name: Convert owner and repo to lowercase
    uses: profy12/lowercase-action@0.6
    with:
      text: ${{ github.repository_owner }}
    id: user-to-lowercase

  - name: Convert repo to lowercase
    uses: profy12/lowercase-action@0.6
    with:
      text: ${{ github.repository_name }}
    id: repo-to-lowercase

  - name: Push Docker Image
    run: |
      docker push ghcr.io/${{ steps.repo-to-lowercase.outputs.text }}/${{ steps.user-to-lowercase.outputs.text }}:${{ env.imageTag }}
    shell: bash
